### ISSUE TITLE
Supporting multiple networks

### ISSUE THREAD

**Issue by eiabea** [erlio/docker-vernemq#20]
I am trying to connect vernemq to 2 different networks

```
services:
  verne:
    image: "erlio/docker-vernemq:1.1.0"
    networks:
       - "external"
       - "default"
```

Due to the fact that the interface is hard coded to eth0 in [vernemq.sh](https://github.com/erlio/docker-vernemq/blob/master/bin/vernemq.sh) the vernemq node gets bound to a potential wrong ip address

I tried to override the IP_ADDRESS variable with "0.0.0.0" in the startup script, but this results in a working mqtt but a failing ranch

Is there any other variable to set to get this to work?
