### ISSUE TITLE
Issues with automatic discovery on GKE

### ISSUE THREAD

**Issue by p-mendes** [erlio/docker-vernemq#47]
After setting up permissions on GKE to enable the default service account and creating the necessary roles (I volunteer to add these steps to the readme file) I cannot get the automatic discovery to work.

The issue seems to lie in the fact that when the `vernemq.sh` script requests the PodList, the `spec.hostname` and `spec.subdomain` properties are missing from the Pod descriptions, and so `kube_pod_names` is always empty. Is there something I'm missing? Could we use `spec.nodeName` instead of `spec.hostname`?

**Comment by ioolkos** [comment]
@p-mendes thanks for opening the issue!
Do you think that the PodList should have the `spec.hostname` and `spec.subdomain`? I mean does it normally? Note, I'm asking as a non-expert in GKE and K8 ;)

**Comment by p-mendes** [comment]
As a non-expert myself, I was basing my assumption that the PodList should contain these fields by default, on the behaviour of the `vernemq.sh` script:

In order for the `VERNEMQ_KUBERNETES_SUBDOMAIN` and `kube_pod_names` variables to be correctly set, `spec.hostname` and `spec.subdomain` **must**  be present, otherwise they'll be set to null. I have tried manually setting `spec.dnsPolicy` to Default and the hostname, but with no success.

I do have `spec.nodeName` for all pods, and this resolves correctly to the corresponding pod IPs. Could this be an option? Still missing `spec.subdomain`, but perhaps setting it manually would be a solution.

**Comment by ioolkos** [comment]
Ok, let's see, then the problem is already clearer. Maybe rings a bell for @dergraf or @larshesel.

The Astarte folks are great Kubernetes experts , so comparing their scripts might give some insights. For instance this one:
 https://github.com/astarte-platform/astarte_vmq_plugin/blob/master/docker/bin/vernemq.sh
Haven't diff'ed the files though.

**Comment by p-mendes** [comment]
After a quick overview of the script from Astarte, there don't seem to be any changes as far as the auto discovery mechanism is concerned. They added a big section which seems to add an SSL listener automatically - quite interesting, but for a separate topic :)

**Comment by ioolkos** [comment]
There's a small change for the K8 service account in the Astarte script: 
https://github.com/astarte-platform/astarte_vmq_plugin/blob/master/docker/bin/vernemq.sh#L19
No idea if this matters here or not.

Hope we can figure this out all together :) 
Next step for me is some reading to do on Kubernetes services and discovery.

**Comment by p-mendes** [comment]
That change doesn't affect this issue actually. In the meantime you can check this out: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods-hostname-and-subdomain-fields

In this doc they say that both `spec.hostname` and `spec.subdomain` are optional settings that must be defined in the Pod config. However I haven't figured out how to apply these settings on a Deployment... If I set a `template.spec.hostname` on a Deployment manifest, all pods have the same hostname, and that doesn't make much sense...

**Comment by p-mendes** [comment]
Sorry pressed Close accidentally...

**Comment by p-mendes** [comment]
OK, I did an attempt using `spec.nodeName` instead of the FQDN and I got this error:

> ** System running to use fully qualified hostnames **
> ** Hostname gke-prod-cluster-0-default-pool-f2b42b87-qxtl is illegal **

This hostame (`gke-prod-cluster-0-default-pool-f2b42b87-qxtl`) resolves to the actual IP address of the pod in question, so I don't see why a FQDN is necessary?

**Comment by ioolkos** [comment]
This is the Erlang cluster complaining, as it is configured for FQDN. (node-name@full-hostname). Do you actually have a nodename? something like `VerneMQ@gke-prod-cluster-0-default-pool-f2b42b87-qxtl`

**Comment by p-mendes** [comment]
Yes, I have changed `vernemq.sh` to get the list of `spec.nodeName` for all pods in the cluster. I am using `VerneMQ@${kube_pod_name}`, where `${kube_pod_name}` is a pod hostname, such as `gke-prod-cluster-0-default-pool-f2b42b87-qxtl`.

Is there a way of disabling the FQDN requirement? In the meantime could you point me in the direction of some example K8S Deployment for launching a VerneMQ Cluster? It would be a great help to see some manifest files that you guys use :grinning:

**Comment by ioolkos** [comment]
Seen a blog post on this lately: https://github.com/nmatsui/kubernetes-vernemq
Then the Astarte stuff I pointed at.

**Comment by popaaaandrei** [comment]
@p-mendes please be so kind and tell me about the `ClusterRole` and `ClusterRoleBinding` permissions in GKE / enable the default service account, I cannot seem to find the references in the Readme.

**Comment by p-mendes** [comment]
Hi @popaaaandrei I'm affraid there are no references. Here are the settings I have used:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # ClusterRoles not bound to namespace?
  # namespace: default
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
...
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```
Hope this helps!
